version: 'build{build}'

image: Ubuntu

platform: x64

before_build:
  - sudo apt install python3 python3-pip -y
  - pip3 install --no-cache-dir --upgrade pip setuptools wheel
  - pip3 install pyqt6 --no-cache-dir
  - pip3 install fbs pyqt6-tools PyInstaller ini-parser --no-cache-dir

build_script:
  - python3 -m PyInstaller -w o!sfc.py --icon o!sfc.ico --onefile --name o!sfc 

artifacts:
  - path: dist/o!sfc.exe
    name: o!sfc
