version: 'build{build}'

image: Visual Studio 2019

before_build:
  - pip install fbs pyqt6 pyside6 PyInstaller

build_script:
  - python -m PyInstaller -w o!sfc.py --icon o!sfc.ico --onefile --name o!sfc 

artifacts:
  - path: dist/o!sfc.exe
    name: o!sfc
